language: python
python:
  - "2.7"
  #- "3.6"

cache: pip

#deploy:
#  provider: script
#  script: bash deploy.sh
#  on:
#    branch: master

addons:
  chrome: stable

before_install:
 - wget http://chromedriver.storage.googleapis.com/81.0.4044.69/chromedriver_linux64.zip -P ~/
 - unzip ~/chromedriver_linux64.zip -d ~/
 - rm ~/chromedriver_linux64.zip
 - sudo mv -f ~/chromedriver /usr/local/share/
 - sudo chmod +x /usr/local/share/chromedriver
 - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
 - sleep 3

env:
  global:
    - RAILS_ENV=test
    - DRIVER=selenium_chrome
    - CHROME_BIN=/usr/local/bin/chromedriver
    - USE_COVERALLS=TRUE

install:
  - pip install --upgrade setuptools
  - pip install -r requirements.txt
  
script:
  - robot ./TestCase/200_open_google.robot