language: python
python:
  - "2.7"
  #- "3.6"

cache: pip

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
    
env:
  global:
    - RAILS_ENV=test
    - DRIVER=selenium_chrome
    - CHROME_BIN=/usr/local/bin/chromedriver
    - USE_COVERALLS=TRUE

install:
  - pip install --upgrade setuptools
  - pip install -r requirements.txt
  
script:
  - robot ./TestCase/200_open_google.robot